### ISSUE TITLE
Choose how we want to bin the targets

### ISSUE THREAD

**Issue by lightningWhite** [lightningWhite/weatherLearning#1]
Since there are a lot of target values in our weather_description.csv file, we will probably want to bin these into fewer categories by grouping similary ones. We need to decide as a group how we want these binned.

For example, we might want to bin "light intensity drizzle" with "light rain" in a category called "rain" or something. 

How many target values do we want to try and identify?

**Comment by lightningWhite** [comment]
Possible categories could be rain, snow, cloudy, clear, stormy (windy or something).
Search through the data to see which ones group together.

**Comment by LiLDorth** [comment]
Here is the current binning system I made. If you feel any are conflicting are go elsewhere let me know


snow | sleet, freezing rain, light shower sleet, heavy snow, light snow, heavy   shower snow, light shower snow, light rain and snow, 'heavy rain and snow,   heavy shower snow
-- | --
rain | shower, ragged shower rain, proximity shower rain, moderate rain, heavy   intensity shower rain, very heavy rain, light intensity drizzle, drizzle,   heavy intensity drizzle, 'light intensity drizzle rain, light intensity   shower rain
cloudy | overcast clouds, broken clouds, scattered clouds
fog | mist
smoke | volcanic ash, haze
tornado | tornado
thunderstorm | ragged thunderstorm, proximity thunderstorm, thunderstorm with light   rain, thunderstorm with heavy rain, thunderstorm with rain, thunderstorm with   light drizzle, thunderstorm with heavy drizzle, thunderstorm with drizzle
sand | proximity sand/dust whirls, sand/dust whirls, dust
sunny | sky is clear, few clouds
windy | squalls

**Comment by lightningWhite** [comment]
This looks fantastic!

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
